---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age12zuxxawdk36hvd4dcp8gprh246xpm4c5ym0pm26anrgsgcrgsu2s0yl9km"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age12zuxxawdk36hvd4dcp8gprh246xpm4c5ym0pm26anrgsgcrgsu2s0yl9km"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age12zuxxawdk36hvd4dcp8gprh246xpm4c5ym0pm26anrgsgcrgsu2s0yl9km"
